model:
  risk_threshold: 0.8
  medium_risk_threshold: 0.5
  model_registry: "./models"
  feature_store: "./feature_store"

monitoring:
  log_predictions: true
  metrics_window: 24h
  alert_threshold:
    accuracy_drop: 0.005
    false_positive_rate: 0.001

api:
  host: "0.0.0.0"
  port: 8501
  workers: 4
